apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "micro-api-globai"
  annotations:
    github.com/project-slug: value
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
